pronunciation = "C"
title_contexts = [".c", ".h"]
function_prefix = "fun"
template_prefix = "template"

[functions]
"free" = "free"
"mallock" = "malloc"
"mem copy" = "memcpy"

[commands]
"arrow" = "->"
"for loop" = ["for (i=0; i<; i++) {}", "left:2, enter, up, end, left:8"]
"iffae" = ["if () {}", "left:2, enter, up, end, left:3"]
"shells" = ["else {}", "left, enter"]
"structure" = ["struct  {};", "left:2, enter, up, end, left:2"]
"semi" = ["", "end:2, semicolon"]
"type def struct" = ["typedef struct {} ;", "left:3, enter, down, end, left:2"]
"return" = ["return ;", "left"]

[types]
"boolean"           = "bool"
"inter" = "int"
"unsigned" = "unsigned"
"void" = "void"
"struct" = "struct"
"enum" = "enum"

[templates]
