title_contexts = ["drracket", ".rkt"]
function_prefix = "fun"

[functions]
"apply" = "apply"
"append" = "append"
"begin" = "begin"
"car" = "car"
"cons" = "cons"
"could er" = "cdr"
"conditional" = "cond"
"define" = "define"
"equal" = "="
"plus" = "+"
"minus" = "-"
"times" = "*"
"if" = "if"
"is list" = "list?"
"is pair" = "pair?"
"is null" = "null?"
"is string" = "string?"
"let" = "let"
"let rec" = "letrec"
"lambda" = "lambda"
"list" = "list"
"map" = "map"
"require" = "require"
"remainder" = "remainder"
"length" = "length"
"error" = "error"
"list tail" = "list-tail"
"provide" = "provide"
"print" = "printf"
"define syntax" = "define-syntax"
"syntax rules" = "syntax-rules"
"set bang" = "set!"
"new" = "new"
"struct" = "struct"

[commands]
"use language" = "#lang "
"language racket" = "#lang racket"